# Generated by Django 4.1 on 2024-01-29 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qipu_api', '0002_contact_relationshiplabel_tag_usertag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_api.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_api.tag')),
            ],
            options={
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_api.media')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_api.tag')),
            ],
            options={
                'unique_together': {('media', 'tag')},
            },
        ),
    ]
